In [23]:
from torchvision.datasets import CIFAR100, CIFAR10, MNIST, QMNIST, KMNIST, FashionMNIST, ImageNet, ImageFolder
from torch.utils.data import Dataset
import numpy as np
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader

In [11]:
training_data = MNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor()
)

52.2%

100.0%


Extracting data/MNIST/raw/train-images-idx3-ubyte.gz to data/MNIST/raw


100.0%
100.0%


Extracting data/MNIST/raw/train-labels-idx1-ubyte.gz to data/MNIST/raw

Extracting data/MNIST/raw/t10k-images-idx3-ubyte.gz to data/MNIST/raw


100.0%

Extracting data/MNIST/raw/t10k-labels-idx1-ubyte.gz to data/MNIST/raw



In [15]:
class DebugDataset(Dataset):
    def __init__(self, dataset, size=256):
        self.img=[]
        self.target=[]
        l=len(dataset)
        ids=np.random.randint(0, l, [size])
        for id_ in ids:
            img, target = dataset[id_]
            self.img.append(img)
            self.target.append(target)
    def __len__(self):
        return len(self.target)
    def __getitem__(self, idx):
        return self.img[idx], self.target[idx]

In [16]:
D=DebugDataset(training_data)

In [24]:
train_dataloader = DataLoader(D, batch_size=64, shuffle=True)

In [27]:
for (img, target) in train_dataloader:
    print(target)

tensor([4, 8, 1, 6, 0, 1, 8, 7, 7, 0, 4, 6, 6, 9, 8, 5, 2, 0, 1, 0, 3, 6, 2, 7,
        2, 1, 8, 9, 1, 0, 7, 6, 8, 7, 5, 8, 1, 1, 6, 0, 0, 6, 6, 1, 6, 3, 0, 7,
        2, 9, 2, 4, 9, 3, 9, 5, 6, 1, 5, 4, 0, 4, 0, 0])
tensor([6, 5, 2, 8, 1, 8, 5, 1, 1, 4, 9, 6, 5, 1, 0, 6, 9, 7, 2, 8, 0, 8, 3, 7,
        1, 0, 3, 5, 6, 6, 7, 8, 6, 3, 8, 9, 9, 7, 2, 2, 1, 0, 3, 0, 3, 0, 7, 9,
        2, 6, 7, 2, 8, 3, 3, 4, 7, 7, 3, 2, 1, 8, 5, 8])
tensor([2, 8, 0, 3, 5, 5, 4, 3, 8, 4, 0, 8, 4, 6, 6, 2, 6, 3, 0, 8, 6, 3, 3, 6,
        3, 0, 5, 5, 6, 3, 0, 9, 0, 4, 5, 4, 0, 9, 9, 6, 1, 6, 0, 4, 1, 6, 0, 7,
        3, 2, 9, 8, 9, 4, 4, 2, 4, 1, 3, 2, 9, 3, 4, 2])
tensor([6, 4, 8, 4, 6, 4, 4, 1, 7, 2, 2, 9, 4, 4, 1, 2, 6, 1, 0, 0, 3, 6, 1, 0,
        4, 0, 9, 6, 0, 5, 7, 8, 1, 8, 6, 9, 9, 0, 9, 4, 5, 3, 6, 3, 1, 0, 3, 4,
        2, 5, 5, 5, 0, 0, 6, 3, 8, 2, 6, 9, 8, 0, 4, 6])


In [30]:
ToTensor()([1])

TypeError: pic should be PIL Image or ndarray. Got <class 'list'>

In [1]:
import numpy as np

In [2]:
A=np.random.random([3,4])

In [7]:
def f(A):
    A+=1

In [8]:
A

array([[0.8122385 , 0.34378085, 0.96024456, 0.40750459],
       [0.87604049, 0.17816906, 0.47871122, 0.82897015],
       [0.64836659, 0.22821158, 0.00127492, 0.79712202]])

In [9]:
f(A)

In [10]:
A

array([[1.8122385 , 1.34378085, 1.96024456, 1.40750459],
       [1.87604049, 1.17816906, 1.47871122, 1.82897015],
       [1.64836659, 1.22821158, 1.00127492, 1.79712202]])